import {
  LayoutDashboard,
  MessagesSquare,
  Workflow,
  Megaphone,
  FileText,
  MessageCircle,
  Users,
  Zap,
  BookOpen,
  Sparkles,
  Plug,
  Code,
  Settings as SettingsIcon,
} from "lucide-react";

export const NAV_ITEMS = [
  { label: "Dashboard", path: "/", icon: LayoutDashboard, testId: "nav-dashboard" },
  { label: "Inbox", path: "/conversations", icon: MessagesSquare, testId: "nav-inbox" },
  { label: "Contacts", path: "/contacts", icon: Users, testId: "nav-contacts" },
  { label: "Campaigns", path: "/campaigns", icon: Megaphone, testId: "nav-campaigns" },
  { label: "Automation", path: "/automation", icon: Zap, testId: "nav-automation" },
  { label: "Journeys", path: "/journeys", icon: Workflow, testId: "nav-journeys" },
  { label: "Templates", path: "/templates", icon: FileText, testId: "nav-templates" },
  { label: "WhatsApp Templates", path: "/templates/whatsapp", icon: MessageCircle, testId: "nav-whatsapp-templates" },
  { label: "Knowledge", path: "/knowledge", icon: BookOpen, testId: "nav-knowledge" },
  { label: "AI Assistant", path: "/assistant", icon: Sparkles, testId: "nav-assistant" },
  { label: "Integrations", path: "/integrations", icon: Plug, testId: "nav-integrations" },
  { label: "Developers", path: "/developers", icon: Code, testId: "nav-developers" },
  { label: "Settings", path: "/settings", icon: SettingsIcon, testId: "nav-settings" },
];
